
package com.itau.core.service.client.jaxws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountsImpl", targetNamespace = "http://server.service.core.itau.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountsImpl {


    /**
     * 
     * @param accountId
     * @param customerId
     * @return
     *     returns com.itau.core.service.server.AccountsImpl.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRead", targetNamespace = "http://server.service.core.itau.com/", className = "com.itau.core.service.server.AccountsImpl.GetRead")
    @ResponseWrapper(localName = "getReadResponse", targetNamespace = "http://server.service.core.itau.com/", className = "com.itau.core.service.server.AccountsImpl.GetReadResponse")
    @Action(input = "http://server.service.core.itau.com/AccountsImpl/getReadRequest", output = "http://server.service.core.itau.com/AccountsImpl/getReadResponse")
    public Account getRead(
        @WebParam(name = "accountId", targetNamespace = "")
        String accountId,
        @WebParam(name = "customerId", targetNamespace = "")
        String customerId);

    /**
     * 
     * @param customerId
     * @return
     *     returns java.util.List<com.itau.core.service.server.AccountsImpl.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://server.service.core.itau.com/", className = "com.itau.core.service.server.AccountsImpl.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://server.service.core.itau.com/", className = "com.itau.core.service.server.AccountsImpl.GetListResponse")
    @Action(input = "http://server.service.core.itau.com/AccountsImpl/getListRequest", output = "http://server.service.core.itau.com/AccountsImpl/getListResponse")
    public List<Account> getList(
        @WebParam(name = "customerId", targetNamespace = "")
        String customerId);

}
