
package com.itau.core.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.itau.core.service.server.AccountsServer;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccountsImplService", targetNamespace = "http://server.service.core.itau.com/", wsdlLocation = "http://localhost:9090/services/accounts?wsdl")
public class AccountsClientImpl
    extends Service
{

    private final static URL ACCOUNTSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOUNTSIMPLSERVICE_EXCEPTION;
    private final static QName ACCOUNTSIMPLSERVICE_QNAME = new QName("http://server.service.core.itau.com/", "AccountsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/services/accounts?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTSIMPLSERVICE_WSDL_LOCATION = url;
        ACCOUNTSIMPLSERVICE_EXCEPTION = e;
    }

    public AccountsClientImpl() {
        super(__getWsdlLocation(), ACCOUNTSIMPLSERVICE_QNAME);
    }

    public AccountsClientImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTSIMPLSERVICE_QNAME, features);
    }

    public AccountsClientImpl(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTSIMPLSERVICE_QNAME);
    }

    public AccountsClientImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTSIMPLSERVICE_QNAME, features);
    }

    public AccountsClientImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountsClientImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountsImpl
     */
    @WebEndpoint(name = "AccountsImplPort")
    public AccountsServer getAccountsImplPort() {
        return super.getPort(new QName("http://server.service.core.itau.com/", "AccountsImplPort"), AccountsServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountsImpl
     */
    @WebEndpoint(name = "AccountsImplPort")
    public AccountsServer getAccountsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.service.core.itau.com/", "AccountsImplPort"), AccountsServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTSIMPLSERVICE_EXCEPTION!= null) {
            throw ACCOUNTSIMPLSERVICE_EXCEPTION;
        }
        return ACCOUNTSIMPLSERVICE_WSDL_LOCATION;
    }

}
